# Generated by Django 5.2.6 on 2026-01-22 15:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_type', models.CharField(choices=[('admin', 'Admin Staff'), ('teacher', 'Teacher'), ('non_teacher', 'Non-Teaching Staff'), ('contractor', 'Contractor'), ('service_provider', 'Service Provider')], max_length=20)),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='payroll.payee')),
            ],
        ),
        migrations.CreateModel(
            name='PayeeOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.payee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_enrollments', to=settings.AUTH_USER_MODEL)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.payee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('is_generated', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payrolls', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='payroll.payee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('payee', 'payroll_period')},
            },
        ),
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bursar_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bursar_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payroll_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='payroll.payrollrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payroll.paymentbatch')),
                ('payroll_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='successful_transactions', to='payroll.payrollrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payroll.payrollrecord')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.salarycomponent')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payee_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayeeSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignment', to='payroll.payee')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.salarystructure')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.salarystructure')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_of_employment', models.DateField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.payee')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_code', models.CharField(max_length=100, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.payee')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('APPROVE', 'Approve'), ('PAY', 'Pay'), ('FAIL', 'Fail'), ('RETRY', 'Retry'), ('VIEW', 'View')], max_length=20)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='payroll_aud_object__481640_idx')],
            },
        ),
    ]
