# Generated by Django 6.0 on 2026-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_chatroom_chatroommessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='room_attachments/'),
        ),
    ]
