# Generated by Django 6.0 on 2026-02-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_chatroommessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('GROUP', 'Group Chat'), ('CONFERENCE', 'Conference Chat')], default='GROUP', max_length=20),
        ),
    ]
