# Generated by Django 6.0 on 2025-12-08 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTARequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('MEETING', 'Meeting Request'), ('ATTENTION', 'Attention Needed'), ('MESSAGE', 'General Message')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(limit_choices_to=models.Q(('role', 'PARENT')), on_delete=django.db.models.deletion.CASCADE, related_name='pta_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'STAFF')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pta_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
