# Generated by Django 6.0 on 2025-12-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_ptarequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbtexamsession',
            old_name='answers',
            new_name='student_answers',
        ),
    ]
