# Generated by Django 6.0 on 2025-12-08 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_rename_answers_cbtexamsession_student_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtquestion',
            name='subject',
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['name', 'academic_year'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code', 'name']},
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='academy_year',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school_class',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='academic_year',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='arm',
            field=models.CharField(blank=True, help_text='e.g., A, B, C or Science, Arts', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='assistant_teacher',
            field=models.TextField(default='superadmin'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='level',
            field=models.CharField(choices=[('kindergarten', 'Kindergarten'), ('nursery', 'Nursery'), ('primary', 'Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary')], default='Kindergarten', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='teacher',
            field=models.TextField(default='superadmin'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective'), ('language', 'Language'), ('arts', 'Arts'), ('sports', 'Sports'), ('vocational', 'Vocational')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='sms.schoolclass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('allow_retake', models.BooleanField(default=False)),
                ('max_retake_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='sms.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='sms.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('objective', 'Objective (single correct)'), ('subjective', 'Subjective (free text)')], max_length=20)),
                ('marks', models.IntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sms.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sms.question')),
            ],
        ),
        migrations.CreateModel(
            name='RetakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.exam')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retake_reviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0.0)),
                ('graded', models.BooleanField(default=False)),
                ('retake_allowed', models.BooleanField(default=False)),
                ('retake_count', models.PositiveIntegerField(default=0)),
                ('is_retake_approved', models.BooleanField(default=False)),
                ('retake_requested', models.BooleanField(default=False)),
                ('question_order', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CBTExamSession',
        ),
        migrations.DeleteModel(
            name='CBTQuestion',
        ),
    ]
