# Generated by Django 6.0 on 2025-12-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brillspay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='class_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SchoolClass',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='internal_reference',
        ),
    ]
