# Generated by Django 6.0 on 2025-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brillspay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
