# Generated by Django 6.0 on 2025-12-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brillspay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='internal_reference',
        ),
    ]
