# Generated by Django 6.0 on 2025-12-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brillspay', '0002_rename_name_productcategory_class_name_and_more'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SchoolClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='exams.schoolclass'),
            preserve_default=False,
        ),
    ]
