# Generated by Django 6.0 on 2025-12-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brillspay', '0003_product_schoolclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SchoolClass',
            new_name='schoolclass',
        ),
    ]
