# Generated by Django 6.0 on 2025-12-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brillspay', '0004_rename_schoolclass_product_schoolclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='schoolclass',
            new_name='SchoolClass',
        ),
    ]
