# Generated by Django 6.0 on 2025-12-29 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brillspay', '0005_rename_schoolclass_product_schoolclass'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SchoolClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_category', to='exams.schoolclass'),
        ),
    ]
