# Generated by Django 6.0 on 2025-12-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brillspay', '0006_alter_product_schoolclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='SchoolClass',
        ),
    ]
