# Generated by Django 6.0 on 2025-12-08 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Verification Code')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='pickup_qrcodes')),
                ('parent', models.ForeignKey(limit_choices_to=models.Q(('role', 'PARENT')), on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to=models.Q(('role', 'STUDENT')), on_delete=django.db.models.deletion.CASCADE, related_name='pickup_authorizations', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role__in', ['ADMIN', 'STAFF'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
