# Generated by Django 6.0 on 2025-12-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupauthorization',
            name='reference',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
