# Generated by Django 6.0 on 2025-12-21 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_alter_pickupauthorization_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupauthorization',
            name='students',
            field=models.ManyToManyField(related_name='pickup_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickupauthorization',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickupstudent',
            name='pickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_students', to='pickup.pickupauthorization'),
        ),
    ]
