# Generated by Django 6.0 on 2025-12-21 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_pickupauthorization_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupauthorization',
            name='students',
        ),
        migrations.AlterField(
            model_name='pickupauthorization',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickupstudent',
            name='pickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='pickup.pickupauthorization'),
        ),
    ]
