"""
Django settings for school_sms project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config 
import os 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True  # config('DEBUG', default=False, cast=bool)

# Allowed hosts
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "newsiest-interlineally-guy.ngrok-free.dev",
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.dev",
]


# CSRF_TRUSTED_ORIGINS = [
#     "https://newsiest-interlineally-guy.ngrok-free.dev",
# ]

# CSRF_TRUSTED_ORIGINS = [
#     "https://*.ngrok-free.dev",
# ]


CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False


CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_FAILURE_VIEW = "brillspay.views.csrf_failure"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',


    # Third-party apps
    # 'rest_framework',
    # 'channels',
    # 'tailwind',             
    # 'storages',             #3# For AWS S3 integration
    

    # Local Apps (The four pillars of this project)
    'exams',                         
    'accounts.apps.AccountsConfig',
    'brillspay.apps.BrillspayConfig',
    'pickup.apps.PickupConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'accounts.middleware.IdleTimeoutMiddleware',  
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE += [
    'accounts.middleware.ProfileCompletionMiddleware',
]


ROOT_URLCONF = 'school_sms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'school_sms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



import os
import logging
from logging.handlers import RotatingFileHandler


LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} | {levelname} | {name} | {module} | {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'system.log'),
            'maxBytes': 5*1024*1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # Central logger for all apps
        'project': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Specific apps (optional)
        'brillspay': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'exams': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'pickups': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Login URLs
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "acccounts:dashboard_redirect"
LOGOUT_REDIRECT_URL = "accounts:login"


# SESSION_COOKIE_SECURE = False   # dev only
# CSRF_COOKIE_SECURE = False      # dev only

# # settings.py
# SESSION_COOKIE_AGE = 1200 # 20 minutes
# SESSION_SAVE_EVERY_REQUEST = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Lagos'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## School config (dynamic)
SCHOOL_NAME = config("SCHOOL_NAME", "The Brills School")
SCHOOL_ADDRESS = config("SCHOOL_ADDRESS", "No 1, Adaba Awotan-Akufo Road. Ibadan. Oyo State")
SCHOOL_LOGO_PATH = BASE_DIR / "static/images/school_logo.png"
SCHOOL_SLOGAN = config("SCHOOL_SLOGAN", "Knowledge is Light")
SCHOOL_ECOMMERCE = config("SCHOOL_ECOMMERCE", "")
PORTAL_DOMAIN = config("PORTAL_DOMAIN", "https://www.thebrillsschool.edu.ng")
SITE_NAME = config("PORTAL_DOMAIN", "https://www.thebrillsschool.edu.ng")
CURRENCY = 'NGN'
CURRENCY_SYMBOL = '₦'
RECEIPT_WATERMARK = "PAID"


# Custom User Model (Best Practice)
AUTH_USER_MODEL = 'accounts.User' 

# Tailwind Config (Use these values for django-tailwind setup)
TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

# Paystack Config (Add this new section)
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY')
PAYSTACK_BASE_URL = config('PAYSTACK_BASE_URL')
PAYSTACK_WEBHOOK = config(
    'PAYSTACK_WEBHOOK_SECRET', default='https://newsiest-interlineally-guy.ngrok-free.dev/brillspay/paystack/webhook/')
PAYSTACK_CALLBACK_URL = config(
    "PAYSTACK_CALLBACK_URL",
    default="https://newsiest-interlineally-guy.ngrok-free.dev/brillspay/paystack/callback/"
)


# --- AWS S3 CONFIGURATION (New Section) ---
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME')
AWS_DEFAULT_ACL = config('AWS_DEFAULT_ACL', default='public-read')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'


# Use local static/media in DEBUG, otherwise switch to S3 if configured
if DEBUG:
    STATIC_URL = "/static/"
    STATICFILES_DIRS = [BASE_DIR / "static"]
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
else:
    # Allow deployment to override storage backends via env
    STATICFILES_STORAGE = config("STATICFILES_STORAGE", default=f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com")
    DEFAULT_FILE_STORAGE = config("DEFAULT_FILE_STORAGE", default=f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com")
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# -----------------------------------------


# Email
EMAIL_BACKEND='django.core.mail.backends.console.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER='your-email@gmail.com'
EMAIL_HOST_PASSWORD='your-app-password'
DEFAULT_FROM_EMAIL='noreply@schoolcommerce.com'

# Redis (for Celery)
REDIS_URL=config("REDIS_URL")

# Backup
BACKUP_ENCRYPTION_KEY=config("BACKUP_ENCRYPTION_KEY")
BACKUP_RETENTION_DAYS=30


# Celery Configuration
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Configuration Options

CELERY_BEAT_SCHEDULE = {
    'cleanup_pickups_every_hour': {
        'task': 'pickups.tasks.cleanup_expired_pickups',
        'schedule': 3600.0,
    },
    'backup_project_daily': {
        'task': 'core.tasks.backup_project_data',
        'schedule': 24*3600.0,  # daily
    },
}



