# Generated by Django 6.0 on 2025-12-08 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('sms', '0004_remove_cbtquestion_subject_alter_schoolclass_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.ForeignKey(blank=True, help_text='The academic class this student belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sms.schoolclass'),
        ),
    ]
