# Generated by Django 6.0 on 2025-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/user_profiles/default_profile.png', help_text='User profile image', null=True, upload_to='user_profiles/'),
        ),
    ]
