# Generated by Django 5.2.6 on 2026-01-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('STUDENT', 'Student'), ('BURSAR', 'Bursar')], default='STUDENT', help_text='Role of the user in the school management system.', max_length=50),
        ),
    ]
