# Generated by Django 6.0 on 2025-12-09 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_student_student_class_user_student_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('role', 'PARENT')), related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parent/Guardian'),
        ),
    ]
