# Generated by Django 6.0 on 2025-12-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examaccess',
            name='reason',
            field=models.TextField(default='o ye olohun'),
            preserve_default=False,
        ),
    ]
