# Generated by Django 5.2.6 on 2026-01-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examaccess',
            old_name='created_at',
            new_name='granted_at',
        ),
    ]
