# Generated by Django 6.0 on 2026-02-05 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_school_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='target_role',
            field=models.CharField(blank=True, default='', help_text="Optional target role: 'students' or 'parents'", max_length=20),
        ),
    ]
