# Generated by Django 6.0 on 2026-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_broadcast_recipients_broadcast_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
    ]
