# Generated by Django 5.2.6 on 2026-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='annual_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
