# Generated by Django 5.2.6 on 2026-01-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leavetype_annual_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='annual_days',
            field=models.PositiveIntegerField(),
        ),
    ]
