# Generated by Django 5.2.6 on 2026-01-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='date_of_employment',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='profile_picture',
        ),
    ]
