# Generated by Django 5.2.6 on 2026-01-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayeeOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.payee')),
            ],
        ),
    ]
