# Generated by Django 5.2.6 on 2026-01-27 11:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_payee_address_remove_payee_date_of_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponent',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage (e.g. 10.00 for 10%)', max_digits=5),
        ),
    ]
