# Generated by Django 5.2.6 on 2026-01-08 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrolllineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='staff',
        ),
        migrations.AlterField(
            model_name='payee',
            name='payee_type',
            field=models.CharField(choices=[('admin', 'Admin Staff'), ('teacher', 'Teacher'), ('non_teacher', 'Non-Teaching Staff'), ('contractor', 'Contractor'), ('service_provider', 'Service Provider')], max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_enrollments', to=settings.AUTH_USER_MODEL)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.payee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
