# Generated by Django 5.2.6 on 2026-01-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payeeonboarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payee',
            name='full_name',
        ),
    ]
