# Generated by Django 5.2.6 on 2026-01-27 11:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salarycomponent_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycomponent',
            name='is_taxable',
        ),
        migrations.RemoveField(
            model_name='salarycomponent',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='is_taxable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage applied to total gross', max_digits=5),
        ),
    ]
