# Generated by Django 5.2.6 on 2026-01-10 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_leaverequest_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollperiod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='status',
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
