# Generated by Django 6.0 on 2026-02-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_salarycomponent_is_taxable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
