# Generated by Django 5.2.6 on 2026-01-10 10:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollgenerationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payroll_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='successful_transactions', to='payroll.payrollrecord'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='payroll.payee'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payroll_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved')], default='generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
